sudo: false

language: node_js
node_js:
  - 12 # use LTS version

before_install:
  - yarn add coveralls -D

script:
  - yarn run build
  - yarn run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npx semantic-release

branches:
  only:
    - master

env:
  global:
    - CI: true
